plt.figure(figsize=(12,5))
plt.plot(df["Temperature_C"][:100], color="orange", label="Temperature")
plt.plot(df["Humidity_pct"][:100], color="pink", label="Humidity")
plt.legend()
plt.title("Temperature vs Humidity")
plt.xlabel("Temperature (°C)")
plt.ylabel("Humidity (%)")
plt.grid(color="#bfbeba")
plt.show()
plt.savefig("Images/temp_vs_humidity.png")